
[Interface]
PrivateKey = qHMVIvtAwZjNewx2YtEPSa53h2ERJZ0UyHzqJ+hFGXg=
Address = 10.20.0.5/24
DNS = 1.1.1.1

[Peer]
PublicKey = H8iHSszcfgapl7hH07UUnwFRVQrFuKCYLjPATYRLwT4=
PresharedKey = lgSns4JZnwzYTeCtDCSd2Hoz9TE3xJkwHZEPjXDIA7Y=
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25
Endpoint = 194.87.216.196:51820