-- G6 — audit авто-коррекции RPH per-op + VIEW повторяющихся ошибок (§26, §0.5).

CREATE TABLE IF NOT EXISTS "resource_limit_adjustments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "error_code" text NOT NULL,
  "op_code" text NOT NULL,
  "op_type_id" integer NOT NULL REFERENCES "resource_op_types" ("id") DEFERRABLE,
  "action" text NOT NULL,
  "old_rph_limit" integer,
  "new_rph_limit" integer,
  "account_id" bigint REFERENCES "accounts" ("id") DEFERRABLE,
  "error_count" integer NOT NULL DEFAULT 0,
  "window_seconds" integer NOT NULL DEFAULT 3600,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS "idx_resource_limit_adjustments_pattern"
  ON "resource_limit_adjustments" ("error_code", "op_code", "created_at" DESC);

CREATE OR REPLACE VIEW "v_recurring_errors_window" AS
SELECT
  ta."error_code",
  rot."code" AS "op_code",
  rot."id" AS "op_type_id",
  rot."rph_limit" AS "current_rph_limit",
  count(DISTINCT ta."id") AS "error_count",
  max(ta."started_at") AS "last_error_at",
  (array_agg(ta."account_id" ORDER BY ta."started_at" DESC))[1] AS "last_account_id"
FROM "task_attempts" ta
INNER JOIN "account_resource_usage" aru ON aru."task_attempt_id" = ta."id"
INNER JOIN "resource_op_types" rot ON rot."id" = aru."op_type_id"
WHERE ta."status" IN ('error', 'timeout')
  AND ta."error_code" IS NOT NULL
  AND ta."started_at" >= now() - interval '1 hour'
GROUP BY ta."error_code", rot."code", rot."id", rot."rph_limit";
