-- =============================================================================
-- Интеграция PG Queue Balancer в существующую Lidogen_main_DB
-- =============================================================================
-- Назначение: накатить таблицы очереди в ТУ ЖЕ БД, где уже живёт
--   платформа лидогенерации (platforms, source_channels, source_messages, ...).
--
-- Отличие от DB/BD_schema.sql (greenfield):
--   * platforms и source_channels НЕ создаются (уже есть) — source_channels
--     только расширяется балансировочными полями (ТЗ §5.1, A8);
--   * используется существующая функция public.update_updated_at()
--     вместо set_updated_at() из BD_schema.sql;
--   * все объекты создаются идемпотентно (IF NOT EXISTS / DO-guard).
--
-- Применять ОДИН раз поверх дампа Lidogen_main_DB.sql:
--   psql "$QUEUE_DATABASE_URL" -f DB/A8_integrate_main_db.sql
-- Полная пересборка с нуля — см. docs(plan)/db-integration-plan.md, режим B.
-- =============================================================================

-- --- 1. ENUM-типы очереди (идемпотентно) ---------------------------------------
DO $$ BEGIN
  CREATE TYPE "account_status" AS ENUM ('active', 'cooldown', 'disabled', 'banned', 'error');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "task_status" AS ENUM ('queued', 'scheduled', 'in_progress', 'retry', 'done', 'failed', 'cancelled', 'stuck');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "attempt_status" AS ENUM ('success', 'error', 'timeout');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE "task_op_account_role" AS ENUM ('primary', 'source', 'target');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- --- 2. Таблицы очереди (source_channels/platforms НЕ трогаем) ------------------
CREATE TABLE IF NOT EXISTS "resource_op_types" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" text UNIQUE NOT NULL,
  "name" text,
  "rph_limit" integer NOT NULL,
  "reserve_percent" numeric NOT NULL DEFAULT 10,
  "is_enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "accounts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "telegram_account_id" text,
  "session_name" text UNIQUE NOT NULL,
  "status" account_status NOT NULL DEFAULT 'active',
  "is_enabled" boolean NOT NULL DEFAULT true,
  "cooldown_until" timestamptz,
  "current_task_id" bigint,
  "last_used_at" timestamptz,
  "last_error" text,
  "last_error_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "task_types" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" text UNIQUE NOT NULL,
  "name" text NOT NULL,
  "description" text,
  "is_enabled" boolean NOT NULL DEFAULT false,
  "default_priority" integer NOT NULL,
  "min_available_resource_percent" integer NOT NULL,
  "requires_specific_account" boolean NOT NULL DEFAULT false,
  "uses_two_accounts" boolean NOT NULL DEFAULT false,
  "max_attempts" integer NOT NULL DEFAULT 5,
  "retry_delay_seconds" integer NOT NULL DEFAULT 10,
  "retry_backoff_multiplier" numeric NOT NULL DEFAULT 2,
  "max_retry_delay_seconds" integer NOT NULL DEFAULT 1800,
  "target_queue_size" integer,
  "max_postpone_count" integer NOT NULL DEFAULT 100,
  "task_timeout_seconds" integer NOT NULL DEFAULT 300,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "task_type_ops" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_type_id" integer NOT NULL,
  "op_type_id" integer NOT NULL,
  "units_per_execution" integer NOT NULL DEFAULT 1,
  "account_role" task_op_account_role NOT NULL DEFAULT 'primary'
);

CREATE TABLE IF NOT EXISTS "task_queue" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_type_id" integer NOT NULL,
  "task_type_code" text NOT NULL,
  "status" task_status NOT NULL DEFAULT 'queued',
  "priority" integer NOT NULL,
  "channel_id" bigint,
  "account_id" bigint,
  "source_account_id" bigint,
  "target_account_id" bigint,
  "payload" jsonb NOT NULL DEFAULT '{}',
  "dedup_key" text,
  "run_after" timestamptz NOT NULL DEFAULT (now()),
  "locked_by" text,
  "locked_at" timestamptz,
  "locked_until" timestamptz,
  "attempt_count" integer NOT NULL DEFAULT 0,
  "postpone_count" integer NOT NULL DEFAULT 0,
  "max_attempts" integer NOT NULL,
  "last_error" text,
  "last_error_at" timestamptz,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "created_by" text,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "task_attempts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" bigint NOT NULL,
  "task_type_id" integer NOT NULL,
  "account_id" bigint NOT NULL,
  "source_account_id" bigint,
  "target_account_id" bigint,
  "attempt_number" integer NOT NULL,
  "status" attempt_status NOT NULL,
  "error_code" text,
  "error_message" text,
  "started_at" timestamptz NOT NULL,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS "account_resource_usage" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "account_id" bigint NOT NULL,
  "op_type_id" integer NOT NULL,
  "task_id" bigint NOT NULL,
  "task_attempt_id" bigint,
  "task_type_id" integer NOT NULL,
  "units" integer NOT NULL DEFAULT 1,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

-- --- 3. Расширение существующей source_channels полями балансировщика (A8) -----
ALTER TABLE "source_channels"
  ADD COLUMN IF NOT EXISTS "assigned_account_id" bigint,
  ADD COLUMN IF NOT EXISTS "extra_data_collected" boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "last_updated_at" timestamptz;

-- --- 4. Внешние ключи (DO-guard, чтобы повторный запуск не падал) ---------------
DO $$ BEGIN
  ALTER TABLE "task_type_ops" ADD FOREIGN KEY ("op_type_id") REFERENCES "resource_op_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_type_ops" ADD FOREIGN KEY ("task_type_id") REFERENCES "task_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_queue" ADD FOREIGN KEY ("task_type_id") REFERENCES "task_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_queue" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_queue" ADD FOREIGN KEY ("source_account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_queue" ADD FOREIGN KEY ("target_account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  -- channel_id -> существующая source_channels.id (int8) из main DB
  ALTER TABLE "task_queue" ADD FOREIGN KEY ("channel_id") REFERENCES "source_channels" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "source_channels" ADD CONSTRAINT "fk_source_channels_assigned_account"
    FOREIGN KEY ("assigned_account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_attempts" ADD FOREIGN KEY ("task_id") REFERENCES "task_queue" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_attempts" ADD FOREIGN KEY ("task_type_id") REFERENCES "task_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_attempts" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_attempts" ADD FOREIGN KEY ("source_account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "task_attempts" ADD FOREIGN KEY ("target_account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "account_resource_usage" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "account_resource_usage" ADD FOREIGN KEY ("op_type_id") REFERENCES "resource_op_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "account_resource_usage" ADD FOREIGN KEY ("task_id") REFERENCES "task_queue" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "account_resource_usage" ADD FOREIGN KEY ("task_attempt_id") REFERENCES "task_attempts" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "account_resource_usage" ADD FOREIGN KEY ("task_type_id") REFERENCES "task_types" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE "accounts" ADD FOREIGN KEY ("current_task_id") REFERENCES "task_queue" ("id") DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- --- 5. Индексы (см. комментарии в DB/BD_schema.sql) ---------------------------
CREATE INDEX IF NOT EXISTS "idx_task_queue_dispatch"
  ON "task_queue" ("status", "run_after", "priority" DESC, "created_at" ASC);
CREATE INDEX IF NOT EXISTS "idx_task_queue_claim_ready"
  ON "task_queue" ("run_after", "priority" DESC, "created_at" ASC)
  WHERE "status" IN ('queued', 'scheduled', 'retry');
CREATE UNIQUE INDEX IF NOT EXISTS "idx_task_queue_dedup_active"
  ON "task_queue" ("dedup_key")
  WHERE "dedup_key" IS NOT NULL AND "status" IN ('queued', 'scheduled', 'retry', 'in_progress');
CREATE INDEX IF NOT EXISTS "idx_task_queue_active_by_type"
  ON "task_queue" ("task_type_id", "status")
  WHERE "status" IN ('queued', 'scheduled', 'retry', 'in_progress');
CREATE INDEX IF NOT EXISTS "idx_task_queue_queued_age"
  ON "task_queue" ("created_at" ASC) WHERE "status" = 'queued';
CREATE INDEX IF NOT EXISTS "idx_task_queue_status_created"
  ON "task_queue" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "idx_task_queue_in_progress_started"
  ON "task_queue" ("started_at") WHERE "status" = 'in_progress';
CREATE INDEX IF NOT EXISTS "idx_task_queue_stuck"
  ON "task_queue" ("status", "started_at") WHERE "status" IN ('in_progress', 'stuck');
CREATE INDEX IF NOT EXISTS "idx_task_queue_high_postpone"
  ON "task_queue" ("postpone_count" DESC)
  WHERE "status" IN ('scheduled', 'retry') AND "postpone_count" > 0;
CREATE INDEX IF NOT EXISTS "idx_task_queue_done_finished"
  ON "task_queue" ("finished_at" DESC) WHERE "status" = 'done';
CREATE INDEX IF NOT EXISTS "idx_task_queue_retry_run_after"
  ON "task_queue" ("run_after") WHERE "status" = 'retry';
CREATE INDEX IF NOT EXISTS "idx_task_queue_channel_active"
  ON "task_queue" ("channel_id")
  WHERE "channel_id" IS NOT NULL AND "status" IN ('queued', 'scheduled', 'retry', 'in_progress');
CREATE INDEX IF NOT EXISTS "idx_task_queue_account_active"
  ON "task_queue" ("account_id", "status")
  WHERE "account_id" IS NOT NULL AND "status" IN ('queued', 'scheduled', 'retry', 'in_progress');

CREATE INDEX IF NOT EXISTS "idx_accounts_pick_available"
  ON "accounts" ("cooldown_until", "last_used_at")
  WHERE "status" = 'active' AND "is_enabled" = true AND "current_task_id" IS NULL;
CREATE INDEX IF NOT EXISTS "idx_accounts_status_cooldown"
  ON "accounts" ("status", "cooldown_until") WHERE "status" IN ('active', 'cooldown');

-- source_channels: только балансировочные индексы (платформенные уже есть в main DB)
CREATE INDEX IF NOT EXISTS "idx_source_channels_assigned_account"
  ON "source_channels" ("assigned_account_id") WHERE "assigned_account_id" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_source_channels_collect_pending"
  ON "source_channels" ("assigned_account_id", "created_at")
  WHERE "assigned_account_id" IS NOT NULL AND "extra_data_collected" = false;
CREATE INDEX IF NOT EXISTS "idx_source_channels_stale_update"
  ON "source_channels" ("last_updated_at" ASC NULLS FIRST)
  WHERE "assigned_account_id" IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "idx_task_type_ops_unique"
  ON "task_type_ops" ("task_type_id", "op_type_id", "account_role");
CREATE INDEX IF NOT EXISTS "idx_account_resource_usage_account_hour"
  ON "account_resource_usage" ("account_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_account_resource_usage_account_op_hour"
  ON "account_resource_usage" ("account_id", "op_type_id", "created_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_account_resource_usage_task"
  ON "account_resource_usage" ("task_id");
CREATE INDEX IF NOT EXISTS "idx_account_resource_usage_attempt"
  ON "account_resource_usage" ("task_attempt_id") WHERE "task_attempt_id" IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS "idx_task_attempts_task_number"
  ON "task_attempts" ("task_id", "attempt_number");
CREATE INDEX IF NOT EXISTS "idx_task_attempts_account_errors"
  ON "task_attempts" ("account_id", "started_at" DESC) WHERE "status" IN ('error', 'timeout');
CREATE INDEX IF NOT EXISTS "idx_task_attempts_type_errors"
  ON "task_attempts" ("task_type_id", "started_at" DESC) WHERE "status" IN ('error', 'timeout');

-- --- 6. Триггеры updated_at: переиспользуем существующую update_updated_at() ----
DO $$ BEGIN
  CREATE TRIGGER "trg_resource_op_types_update_updated_at" BEFORE UPDATE ON "resource_op_types"
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER "trg_accounts_update_updated_at" BEFORE UPDATE ON "accounts"
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER "trg_task_types_update_updated_at" BEFORE UPDATE ON "task_types"
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE TRIGGER "trg_task_queue_update_updated_at" BEFORE UPDATE ON "task_queue"
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- source_channels уже имеет trg_source_channels_update_updated_at в main DB — не дублируем.

-- --- 7. Мониторинговые VIEW (§26) ----------------------------------------------
-- Идентичны DB/BD_schema.sql. CREATE OR REPLACE — безопасно при повторном накате.
CREATE OR REPLACE VIEW "v_queue_size_by_status" AS
SELECT "status", count(*) AS "tasks_count" FROM "task_queue" GROUP BY "status";

CREATE OR REPLACE VIEW "v_queue_size_by_type" AS
SELECT "task_type_code", "status", count(*) AS "tasks_count"
FROM "task_queue"
WHERE "status" IN ('queued', 'scheduled', 'retry', 'in_progress')
GROUP BY "task_type_code", "status";

CREATE OR REPLACE VIEW "v_queue_metrics" AS
SELECT
  count(*) FILTER (WHERE "status" IN ('queued', 'scheduled', 'retry', 'in_progress')) AS "queue_size_total",
  count(*) FILTER (WHERE "status" = 'queued')      AS "queued_count",
  count(*) FILTER (WHERE "status" = 'scheduled')   AS "scheduled_count",
  count(*) FILTER (WHERE "status" = 'in_progress') AS "in_progress_count",
  count(*) FILTER (WHERE "status" = 'retry')       AS "retry_tasks_count",
  count(*) FILTER (WHERE "status" = 'stuck')       AS "stuck_tasks_count",
  count(*) FILTER (WHERE "status" = 'failed')      AS "failed_tasks_count",
  count(*) FILTER (WHERE "status" IN ('scheduled', 'retry') AND "postpone_count" > 0) AS "postponed_tasks_count",
  count(*) FILTER (WHERE "status" = 'done' AND "finished_at" >= now() - interval '5 minutes') AS "done_tasks_last_5_min",
  COALESCE(
    EXTRACT(EPOCH FROM (now() - min("created_at") FILTER (WHERE "status" IN ('queued', 'scheduled'))))::bigint,
    0
  ) AS "oldest_queued_task_age_seconds"
FROM "task_queue";

CREATE OR REPLACE VIEW "v_high_postpone_tasks" AS
SELECT "id", "task_type_code", "status", "postpone_count", "last_error", "run_after", "created_at"
FROM "task_queue"
WHERE "status" IN ('scheduled', 'retry') AND "postpone_count" > 0
ORDER BY "postpone_count" DESC;

CREATE OR REPLACE VIEW "v_account_op_usage_last_hour" AS
SELECT
  "a"."id" AS "account_id", "a"."session_name", "a"."status" AS "account_status",
  "rot"."id" AS "op_type_id", "rot"."code" AS "op_code", "rot"."rph_limit", "rot"."reserve_percent",
  floor("rot"."rph_limit" * (1 - "rot"."reserve_percent" / 100.0))::int AS "effective_rph",
  COALESCE("u"."used_last_hour", 0) AS "used_last_hour",
  floor("rot"."rph_limit" * (1 - "rot"."reserve_percent" / 100.0))::int - COALESCE("u"."used_last_hour", 0) AS "available_resource",
  CASE WHEN floor("rot"."rph_limit" * (1 - "rot"."reserve_percent" / 100.0)) > 0
    THEN round((floor("rot"."rph_limit" * (1 - "rot"."reserve_percent" / 100.0)) - COALESCE("u"."used_last_hour", 0))::numeric
      / floor("rot"."rph_limit" * (1 - "rot"."reserve_percent" / 100.0)) * 100, 2)
    ELSE 0 END AS "available_resource_percent"
FROM "accounts" "a"
CROSS JOIN "resource_op_types" "rot"
LEFT JOIN (
  SELECT "account_id", "op_type_id", SUM("units") AS "used_last_hour"
  FROM "account_resource_usage" WHERE "created_at" >= now() - interval '1 hour'
  GROUP BY "account_id", "op_type_id"
) "u" ON "u"."account_id" = "a"."id" AND "u"."op_type_id" = "rot"."id"
WHERE "rot"."is_enabled" = true;

CREATE OR REPLACE VIEW "v_account_resource_summary" AS
SELECT "account_id", "session_name", "account_status",
  min("available_resource_percent") AS "worst_available_percent",
  bool_or("available_resource" <= 0) AS "any_op_exhausted",
  count(*) FILTER (WHERE "available_resource" <= 0) AS "exhausted_ops_count"
FROM "v_account_op_usage_last_hour"
GROUP BY "account_id", "session_name", "account_status";

CREATE OR REPLACE VIEW "v_accounts_overview" AS
SELECT
  count(*) FILTER (WHERE "status" = 'active' AND "is_enabled" = true) AS "active_accounts_count",
  count(*) FILTER (WHERE "status" = 'cooldown')  AS "accounts_in_cooldown",
  count(*) FILTER (WHERE "status" = 'banned')    AS "banned_accounts_count",
  count(*) FILTER (WHERE "status" = 'disabled')  AS "disabled_accounts_count",
  count(*) FILTER (WHERE "status" = 'error')     AS "error_accounts_count",
  (SELECT count(*) FROM "v_account_resource_summary" WHERE "any_op_exhausted" = true) AS "accounts_without_resource"
FROM "accounts";

CREATE OR REPLACE VIEW "v_channel_capacity_usage" AS
SELECT
  (
    SELECT count(*) FROM "accounts"
    WHERE "status" = 'active' AND "is_enabled" = true
  ) AS "active_accounts_count",
  COALESCE((
    SELECT count(*)
    FROM "source_channels" "sc"
    INNER JOIN "accounts" "a" ON "a"."id" = "sc"."assigned_account_id"
    WHERE "sc"."is_active" = true
      AND "sc"."assigned_account_id" IS NOT NULL
      AND "a"."status" = 'active' AND "a"."is_enabled" = true
  ), 0)::bigint AS "assigned_channels_total";

CREATE OR REPLACE VIEW "v_account_error_rate_last_hour" AS
SELECT "account_id", count(*) AS "attempts_last_hour",
  count(*) FILTER (WHERE "status" IN ('error', 'timeout')) AS "errors_last_hour",
  CASE WHEN count(*) > 0 THEN round(count(*) FILTER (WHERE "status" IN ('error', 'timeout'))::numeric / count(*) * 100, 2) ELSE 0 END AS "error_rate_percent"
FROM "task_attempts" WHERE "started_at" >= now() - interval '1 hour'
GROUP BY "account_id";

CREATE OR REPLACE VIEW "v_task_type_error_rate_last_hour" AS
SELECT "task_type_id", count(*) AS "attempts_last_hour",
  count(*) FILTER (WHERE "status" IN ('error', 'timeout')) AS "errors_last_hour",
  CASE WHEN count(*) > 0 THEN round(count(*) FILTER (WHERE "status" IN ('error', 'timeout'))::numeric / count(*) * 100, 2) ELSE 0 END AS "error_rate_percent"
FROM "task_attempts" WHERE "started_at" >= now() - interval '1 hour'
GROUP BY "task_type_id";

CREATE TABLE IF NOT EXISTS "resource_limit_adjustments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "error_code" text NOT NULL,
  "op_code" text NOT NULL,
  "op_type_id" integer NOT NULL REFERENCES "resource_op_types" ("id") DEFERRABLE,
  "action" text NOT NULL,
  "old_rph_limit" integer,
  "new_rph_limit" integer,
  "account_id" bigint REFERENCES "accounts" ("id") DEFERRABLE,
  "error_count" integer NOT NULL DEFAULT 0,
  "window_seconds" integer NOT NULL DEFAULT 3600,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX IF NOT EXISTS "idx_resource_limit_adjustments_pattern"
  ON "resource_limit_adjustments" ("error_code", "op_code", "created_at" DESC);

CREATE OR REPLACE VIEW "v_recurring_errors_window" AS
SELECT
  ta."error_code",
  rot."code" AS "op_code",
  rot."id" AS "op_type_id",
  rot."rph_limit" AS "current_rph_limit",
  count(DISTINCT ta."id") AS "error_count",
  max(ta."started_at") AS "last_error_at",
  (array_agg(ta."account_id" ORDER BY ta."started_at" DESC))[1] AS "last_account_id"
FROM "task_attempts" ta
INNER JOIN "account_resource_usage" aru ON aru."task_attempt_id" = ta."id"
INNER JOIN "resource_op_types" rot ON rot."id" = aru."op_type_id"
WHERE ta."status" IN ('error', 'timeout')
  AND ta."error_code" IS NOT NULL
  AND ta."started_at" >= now() - interval '1 hour'
GROUP BY ta."error_code", rot."code", rot."id", rot."rph_limit";
